# Pandas LeetCode Practice
This notebook contains small pandas exercises focused on one concept at a time.

Each example is intentionally short so you can understand the pandas method and its purpose quickly.

# 2877 - Create DataFrame from a List

In [ ]:
import pandas as pd

# Create a DataFrame from a list of rows
student_data = [[1, 55], [2, 60], [3, 65]]
df = pd.DataFrame(student_data, columns=['student_id', 'age'])
print(df)

   student_id  age
0           1   55
1           2   60
2           3   65

# 2878 - Get the Size of a DataFrame

In [ ]:
import pandas as pd

# DataFrame size = (rows, columns)
df = pd.DataFrame([[1, 55], [2, 60], [3, 65]], columns=['student_id', 'age'])
print(df.shape)
print(list(df.shape))

[3, 2]

# 2879 - Display the First Three Rows

In [ ]:
import pandas as pd

# Display the first 3 rows of the DataFrame
employees = pd.DataFrame({
    'employee_id': [1, 2, 3, 4],
    'employee_name': ['Rohit', 'Rohit', 'Rohit', 'Rohit'],
    'employee_salary': [1000, 2000, 3000, 4000],
    'department': ['IT', 'HR', 'Finance', 'Marketing']
})

print(employees.head(3))
print('\nUsing slicing:')
print(employees[:3])

   employee_id employee_name  employee_salary department
0            1         Rohit             1000         IT
1            2         Rohit             2000         HR
2            3         Rohit             3000    Finance

   employee_id employee_name  employee_salary department
0            1         Rohit             1000         IT
1            2         Rohit             2000         HR
2            3         Rohit             3000    Finance

# 2880 - Select Data

In [ ]:
import pandas as pd

# Select rows where student_age == 21 and keep only two columns
students = pd.DataFrame({
    'student_id': [1, 2, 3, 4],
    'student_name': ['Rohit', 'Rohit', 'Rohit', 'Rohit'],
    'student_age': [20, 21, 22, 23],
    'student_department': ['IT', 'HR', 'Finance', 'Marketing']
})

result = students.loc[students['student_age'] == 21, ['student_id', 'student_name']]
print(result)

   student_id student_name
1           2        Rohit

# 2881 - Create A New Column

In [ ]:
import pandas as pd

# Add a new column based on an existing one
employees = pd.DataFrame({
    'employee_name': ['Rohit', 'Rohit', 'Rohit', 'Rohit'],
    'employee_salary': [1000, 2000, 3000, 4000]
})
employees['bonus'] = employees['employee_salary'] * 2
print(employees)

  employee_name  employee_salary  bonus
0         Rohit             1000   2000
1         Rohit             2000   4000
2         Rohit             3000   6000
3         Rohit             4000   8000

# 2882 - Drop Duplicate Rows
- Remove duplicate values from the email column and keep only the first occurrence.

In [ ]:
import pandas as pd

# Remove duplicate emails and keep the first occurrence
customers = pd.DataFrame({
    'customer_id': [1, 2, 3, 4],
    'customer_name': ['Rohit', 'Rohit', 'Rohit', 'Rohit'],
    'email': ['rohit@gmail.com', 'rohit@gmail.com', 'rohit@yahoo.com', 'rohit@domain.com']
})

print(customers.drop_duplicates(subset=['email']))

   customer_id customer_name             email
0            1         Rohit   rohit@gmail.com
2            3         Rohit   rohit@yahoo.com
3            4         Rohit  rohit@domain.com

# 2883 - Drop Missing Data

In [ ]:
import pandas as pd

# Drop rows where the name is missing
students = pd.DataFrame({
    'student_id': [1, 2, 3, 4],
    'name': ['Rohit', None, 'Alice', None],
    'age': [20, 21, 22, 23]
})

print(students.dropna(subset=['name']))

   student_id   name  age
0           1  Rohit   20
2           3  Alice   22

# 2884 - Modify Columns

In [ ]:
import pandas as pd

# Double the salary values in-place
employees = pd.DataFrame({
    'name': ['Abhishek', 'Rohit', 'Alice', 'Bob'],
    'salary': [1000, 2000, 3000, 4000]
})
employees['salary'] = employees['salary'] * 2
print(employees)

       name  salary
0  Abhishek    2000
1     Rohit    4000
2     Alice    6000
3       Bob    8000

# 2885 - Rename Columns

In [ ]:
import pandas as pd

# Rename columns for better readability
students = pd.DataFrame({
    'id': [1, 2, 3, 4],
    'first': ['Rohit', 'Alice', 'Bob', 'Charlie'],
    'last': ['Sharma', 'Smith', 'Johnson', 'Williams'],
    'age': [20, 21, 22, 23]
})

students.rename(columns={
    'id': 'student_id',
    'first': 'first_name',
    'last': 'last_name',
    'age': 'age_in_years'
}, inplace=True)
print(students)

   student_id first_name last_name  age_in_years
0           1      Rohit    Sharma            20
1           2      Alice     Smith            21
2           3        Bob   Johnson            22
3           4    Charlie  Williams            23

# 2886 - Change Data Type

In [ ]:
import pandas as pd

# Convert float values to integers
students = pd.DataFrame({
    'student_id': [1, 2, 3, 4],
    'name': ['Rohit', None, 'Alice', None],
    'age': [20, 21, 22, 23],
    'grade': [73.5, 85.0, 92.0, 78.9]
})
students['grade'] = students['grade'].astype('int')
print(students)

   student_id   name  age  grade
0           1  Rohit   20     73
1           2   None   21     85
2           3  Alice   22     92
3           4   None   23     78

# 2887 - Fill Missing Data

In [ ]:
import pandas as pd

# Fill missing values with 0
products = pd.DataFrame({
    'name': ['Laptop', 'Smartphone', 'Tablet', 'Headphones'],
    'quantity': [10, None, None, 30],
    'price': [1000, 800, 500, 200]
})
products['quantity'] = products['quantity'].fillna(0)
print(products)

         name  quantity  price
0      Laptop      10.0   1000
1  Smartphone       0.0    800
2      Tablet       0.0    500
3  Headphones      30.0    200

# 2888 - Reshape Data: Concatenate

In [ ]:
import pandas as pd

# Concatenate two DataFrames vertically
students_1 = pd.DataFrame({
    'student_id': [1, 2, 3],
    'name': ['Rohit', 'Alice', 'Bob'],
    'age': [20, 21, 22]
})
students_2 = pd.DataFrame({
    'student_id': [4, 5, 6],
    'name': ['Charlie', 'David', 'Eva'],
    'age': [23, 24, 25]
})

result = pd.concat([students_1, students_2], ignore_index=True)
print(result)

   student_id     name  age
0           1    Rohit   20
1           2    Alice   21
2           3      Bob   22
3           4  Charlie   23
4           5    David   24
5           6      Eva   25

# 2889 - Reshape Data: Pivot

In [ ]:
import pandas as pd

# Pivot the data so each city becomes a column; pandas may sort the column labels
weather = pd.DataFrame({
    'city': ['New York', 'Los Angeles', 'Chicago', 'Houston'],
    'temperature': [30, 25, 20, 35],
    'month': ['January', 'February', 'March', 'April']
})

pivoted_weather = weather.pivot(index='month', columns='city', values='temperature')
print(pivoted_weather)

city      Chicago  Houston  Los Angeles  New York
month
April         NaN     35.0          NaN       NaN
February      NaN      NaN         25.0       NaN
January       NaN      NaN          NaN      30.0
March        20.0      NaN          NaN       NaN

# 2890 - Reshape Data: Melt

In [ ]:
import pandas as pd

report = pd.DataFrame({
    'product': ['Laptop', 'Smartphone', 'Tablet', 'Headphones'],
    'quarter_1': [1000, 800, 500, 200],
    'quarter_2': [1200, 900, 600, 250],
    'quarter_3': [1100, 850, 550, 220],
    'quarter_4': [1300, 950, 650, 300]
})

# Convert wide data to long format: one row per product-quarter pair
reshaped_report = report.melt(
    id_vars=['product'],
    value_vars=['quarter_1', 'quarter_2', 'quarter_3', 'quarter_4'],
    var_name='quarter',
    value_name='sales'
)
print(reshaped_report)

       product    quarter  sales
0       Laptop  quarter_1   1000
1   Smartphone  quarter_1    800
2       Tablet  quarter_1    500
3   Headphones  quarter_1    200
4       Laptop  quarter_2   1200
5   Smartphone  quarter_2    900
6       Tablet  quarter_2    600
7   Headphones  quarter_2    250
8       Laptop  quarter_3   1100
9   Smartphone  quarter_3    850
10      Tablet  quarter_3    550
11  Headphones  quarter_3    220
12      Laptop  quarter_4   1300
13  Smartphone  quarter_4    950
14      Tablet  quarter_4    650
15  Headphones  quarter_4    300

# 2891 - Method Chaining

In [ ]:
import pandas as pd

animals = pd.DataFrame({
    'name': ['husky', 'tommy', 'bob', 'jonathan'],
    'species': ['dog', 'cat', 'dog', 'cat'],
    'age': [3, 5, 2, 4],
    'weight': [300, 100, 250, 50]
})

# Filter animals heavier than 100 kg, sort by weight descending, and reset the index
result = (
    animals.query('weight > 100')
    .sort_values('weight', ascending=False)
    .reset_index(drop=True)
)
print(result)

    name spacies  age  weight
0  husky     dog    3     300
1    bob     dog    2     250